### ISSUE TITLE
Add action to publish docs

### ISSUE THREAD

**Issue by MizsakPeterEcon** [daniel-mizsak/python-package-template#2]
Add a Github action to automatically publish the docs, possibly as a GitHub page:

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

**Comment by daniel-mizsak** [comment]
Currently I am using [Read the Docs](https://docs.readthedocs.io/en/stable/tutorial/index.html). It does automatic documentation building and publishing with the `readthedocs.yml` file.

I used GitHub Pages before, but when I was playing around with it I was only able to publish while having the built static code part of the repository or part of a feature branch.
And I did not like the idea of having the html code in my repository.

Did you try publishing from artifact? I guess that could be a nice solution you just have to be aware not to consume all your GitHub space it is using.

**Comment by daniel-mizsak** [comment]
Hmm, but to me it seems like that the [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) still creates the newly built static files on a feature branch for serving it with GH Pages.

I feel like it is a little annoying to have a dedicated branch just for this, but at the same time it is convenient that everything stays within GH.

I do not think that I will experiment with making the docs workflow for now, but feel free to contribute either [here](https://github.com/daniel-mizsak/python-package-template) or to my [workflows](https://github.com/daniel-mizsak/workflows) repository where the current CI workflow is referenced from. 😄

**Comment by daniel-mizsak** [comment]
Some minor remarks:
- `peaceiris/actions-gh-pages@v3` assumes that the repository already has the `gh-pages` branch, and will run to error if it does not
- Workflow permissions to the repository have to be set to `Read and write permissions` as detailed [on stackoverflow](https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot)
